### ISSUE TITLE
suggestion - replace done with toString

### ISSUE THREAD

**Issue by akashmugu** [Marvin9/mod-url#1]
replacing done with toString (just the function name) offers an important advantage. if a user forgets to call it explicitly in a place like console.log, browser / node does it automatically for the user

it's more intuitive and in sync other lib apis

**Comment by Marvin9** [comment]
Thanks for that suggestion. 😃

- [x] added toString()
- [ ] documentation remaining.
- [ ] keep done() as we cannot completely remove.
